name: Verify Server Status

on:
  pull_request:
    branches:
      - develop
    types: [opened, reopened, synchronize]

  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Build
        run: go build -o main

      - name: Run Go Server
        run: nohup ./main &

      - name: Wait for server to start
        run: sleep 5

      - name: Verify server is running
        run: |
          RESPONSE=$(curl -s http://localhost:8000/status)
          if echo "$RESPONSE" | grep -q '"status":"OK"'; then
            echo "Server is running and returned OK"
          else
            echo "Server did not return expected status"
            exit 1
          fi
